volumes:
  static:
  media:
  pg_data:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: podzorovmihail/z-dachnik_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  # frontend:
  #   env_file: .env
  #   image: podzorovmihail/z-dachnik_frontend
  #   command: cp -r /app/build/. /frontend_static/
  #   volumes:
  #     - static:/frontend_static
  gateway:
    depends_on:
      - backend
      # - frontend
    image: podzorovmihail/z-dachnik_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media